django/webdev/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^wikiNet/',include('wikiNet.urls')),
]

django/wikiNet/urls.py
from django.conf.urls import url

from . import views

app_name = 'wikiNet'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^search/',views.search, name='search'),
    url(r'^route/',views.route, name='route'),
]

django/wikiNet/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

django/wikiNet/views.py
from django.shortcuts import render
from django.template import loader
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.utils import timezone
import sys, os
import cPickle as pkl
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
import knowledgeGraph

sys.modules['knowledgeGraph']=knowledgeGraph
with open('wikiNet/class_dev.pkl') as f:
    G = pkl.load(f)

def index(request):
    return render(request, 'index.html')

def search(request):
    global G
    query = request.GET.get('query', None)
    docID = G.matchQuery(query)
    dID,aID = G.searchRelated(docID)
    queryAnchor = (G.idx2url[G.row2idx[docID]], G.idx2url[G.row2idx[docID]][6:].replace("_", " "))
    dList = zip([G.idx2url[G.row2idx[i]] for i in dID], [G.idx2url[G.row2idx[i]][6:].replace("_", " ") for i in dID])
    aList = zip([G.idx2url[G.row2idx[i]] for i in aID], [G.idx2url[G.row2idx[i]][6:].replace("_", " ") for i in aID])
    return render(request, 'matchResult.html',{'queryTitle': queryAnchor, 'dList': dList, 'aList': aList})
    

def route(request):
    global G
    src = request.GET.get('src', None)
    dst = request.GET.get('dst', None)
    srcID = G.matchQuery(src)
    # print srcID
    dstID = G.matchQuery(dst)
    # print dstID
    route = G.searchRoute(srcID, dstID)
    srcAnchor = (G.idx2url[G.row2idx[srcID]], G.idx2url[G.row2idx[srcID]][6:].replace("_", " "))
    dstAnchor = (G.idx2url[G.row2idx[dstID]], G.idx2url[G.row2idx[dstID]][6:].replace("_", " "))
    if route != []:
        route.append(dstID)
        routeList = zip([G.idx2url[G.row2idx[i]] for i in route], [G.idx2url[G.row2idx[i]][6:].replace("_", " ") for i in route])
    else:
        routeList = []
    return render(request,'routeResult.html',{'isRoute': len(route), 'srcTitle': srcAnchor, 'dstTitle': dstAnchor, 'routeList': routeList})
    

django/wikiNet/templates/index.html
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>WikiNet: Wikipedia as a network</title>
    <link href="http://cs.nyu.edu/~cz1389/next_files/xz.css" rel="stylesheet" type="text/css">
    {% load static %}<link href=" {% static 'custom.css' %}" rel="stylesheet" type="text/css">
</head>

<body>

<div class="container700 vcard">

    <div class="titletext fn" style="text-align: center">
            WikiNet: <span style="font-size: 0.75em">Wikipedia as a network</span>
    </div>

    <div id="section-links">
        <div class="sectionContainer">
            <div class="section selected">
                Portal »
            </div>
            <div class="section">
                <br> 
            </div>
            <br>
            <div class="section">
                {% load static %}<a href=" {% static 'about.html' %}">About it</a>
            </div>
            <div class="section">
                {% load static %}<a href="{% static 'WikiNet.pdf' %}">More About it</a>
            </div>
            <br>
            <div class="section">Authors:<br>
                <ul style="list-style: none;">
                    <li><a href="mailto:chen.zhang@nyu.edu">Chen ZHANG</a></li>
                    <li><a href="mailto:gy552@nyu.edu">Guang YANG</a></li>
                </ul>
            </div>
            <br>
        </div>
    </div>

    <div class='content'>
        <div>
            <p>WikiNet is a project, in responce to the Graduate Course of 
                <a href="http://cs.nyu.edu/courses/spring17/CSCI-GA.2580-001/">Web Search Engine</a> 
                at New York University Courant Institute of Mathematical Science, 
                seeking to explore <a href="https://en.wikipedia.org">Wikipedia</a> as a graph of knowledge.
                We implement a search engine for the relations in the graph. 
                So far, we provide two search functions:</p>
            
        </div>
        
        <div class="Box">
            <div class="searchBox">
                 <p> Match your keywords with the most related wikipedia page in our dataset, 
                    then list the top 20 most related pages it derives into 
                    and the top 20 most related pages that can derive into the exact match. </p>
                Search here for most related pages. 
                <br>
                <form action=" {% url 'wikiNet:search' %} " method="get">
                <table>
                    <tr>
                        <td><input id="query" type="text" name="query" placeholder="Keywords"></td>
                    </tr>
                    <tr>
                        <td><input type="submit" value="Search for related Pages! "></td>
                    </tr>
                </table>
                </form>
            </div>
            
            <div class="searchBox">
                <p>Take a pair of keywords. Match them with the most related wikipedia page in our dataset respectively. 
                    Then return the most related path bewteen the two pages. </p>
                Search here for the most related path. 
                <br>
                <form action=" {% url 'wikiNet:route' %} " method="get">
                <table>
                    <tr>
                        <td><input id="src" type="text" name="src" placeholder="Source"></td>
                    </tr>
                    <tr>
                        <td><input id="dst" type="text" name="dst" placeholder="Destination"></td> 
                    </tr>
                    <tr>
                        <td><input type="submit" value="Search for most related Path! "></td>
                    </tr>
                </table>
                </form>
            </div>
            <div style="clear:both;"> </div>
        </div>
    </div>

    <br>
    <div style="clear:both;"> </div>
</div>
    <div class="webfooter">
        C. Zhang and G. Yang 
        <br>
        Powered by Django
    </div>
</body>
</html>

django/wikiNet/templates/matchResult.html
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Search results for {{queryTitle.1}} - WikiNet</title>
    <link href="http://cs.nyu.edu/~cz1389/next_files/xz.css" rel="stylesheet" type="text/css">
    {% load static %}<link href=" {% static 'custom.css' %}" rel="stylesheet" type="text/css">
</head>

<body>

<div class="container700 vcard">

    <div class="titletext fn" style="text-align: center">
            WikiNet: <span style="font-size: 0.75em">Wikipedia as a Network</span>
    </div>

    <div id="section-links">
        <div class="sectionContainer">
            <div class="section">
                <a href="{% url 'wikiNet:index' %}">Portal</a>
            </div>
            <div class="section selected">
                Results » 
            </div>
            <br>
            <div class="section">
                {% load static %}<a href=" {% static 'about.html' %}">About it</a>
            </div>
            <div class="section">
                 {% load static %}<a href="{% static 'WikiNet.pdf' %}">More About it</a>
            </div>
            <br>
            <div class="section">Authors:<br>
                <ul style="list-style: none;">
                    <li><a href="mailto:chen.zhang@nyu.edu">Chen ZHANG</a></li>
                    <li><a href="mailto:gy552@nyu.edu">Guang YANG</a></li>
                </ul>
            </div>
            <br>
        </div>
    </div>

    <div class='content'>
        <div>
            <p>Your query is matched with <a href="https://en.wikipedia.org{{queryTitle.0}}">{{queryTitle.1}}</a> in our database. </p>

        </div>

        <div class="Box">
            <div class="searchBox">
                The page can derive into
                <br>
                <ol>
                    {% for d in dList %}
                        <li>
                                <a href="https://en.wikipedia.org{{d.0}}">{{d.1}}</a>
                        </li>
                    {% endfor %}
                    <tr>
                </ol>
            </div>
            
            <div class="searchBox">
                The page can be derived from 
                <br>
                <ol>
                    {% for d in aList %}
                        <li>
                            <a href="https://en.wikipedia.org{{d.0}}">{{d.1}}</a>
                        </li>
                    {% endfor %}
                    <tr>
                </ol>
            </div>
            <div style="clear:both;"> </div>
        </div>

        <h3>Continue exploring WikiNet: </h3>
            
        <div class="Box">
            <div class="searchBox">
                Search here for most related pages. 
                <br>
                <form action=" {% url 'wikiNet:search' %} " method="get">
                <table>
                    <tr>
                        <td><input id="query" type="text" name="query" placeholder="Keywords"></td>
                    </tr>
                    <tr>
                        <td><input type="submit" value="Search for related Pages! "></td>
                    </tr>
                </table>
                </form>
            </div>
            
            <div class="searchBox">
                Search here for the most related path. 
                <br>
                <form action=" {% url 'wikiNet:route' %} " method="get">
                <table>
                    <tr>
                        <td><input id="src" type="text" name="src" placeholder="Source"></td>
                    </tr>
                    <tr>
                        <td><input id="dst" type="text" name="dst" placeholder="Destination"></td> 
                    </tr>
                    <tr>
                        <td><input type="submit" value="Search for most related Path! "></td>
                    </tr>
                </table>
                </form>
            </div>
            <div style="clear:both;"> </div>
        </div>
    </div>

    <br>
    <div style="clear:both;"> </div>
</div>
    <div class="webfooter">
        C. Zhang and G. Yang 
        <br>
        Powered by Django
    </div>
</body>
</html>

django/wikiNet/templates/routeResult.html
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Route from for {{srcTitle.1}} to {{dstTitle.1}} - WikiNet</title>
    <link href="http://cs.nyu.edu/~cz1389/next_files/xz.css" rel="stylesheet" type="text/css">
    {% load static %}<link href=" {% static 'custom.css' %}" rel="stylesheet" type="text/css">
</head>

<body>

<div class="container700 vcard">

    <div class="titletext fn" style="text-align: center">
            WikiNet: <span style="font-size: 0.75em">Wikipedia as a Network</span>
    </div>

    <div id="section-links">
        <div class="sectionContainer">
            <div class="section">
                <a href="{% url 'wikiNet:index' %}">Portal</a>
            </div>
            <div class="section selected">
                Results » 
            </div>
            <br>
            <div class="section">
                {% load static %}<a href=" {% static 'about.html' %}">About it</a>
            </div>
            <div class="section">
                {% load static %}<a href="{% static 'WikiNet.pdf' %}">More About it</a>
            </div>
            <br>
            <div class="section">Authors:<br>
                <ul style="list-style: none;">
                    <li><a href="mailto:chen.zhang@nyu.edu">Chen ZHANG</a></li>
                    <li><a href="mailto:gy552@nyu.edu">Guang YANG</a></li>
                </ul>
            </div>
            <br>
        </div>
    </div>

    <div class='content'>
        <div>
            <p>Your source page is matched with <a href="https://en.wikipedia.org{{srcTitle.0}}">{{srcTitle.1}}</a>. 
            <br>
            And your destination page is matched with <a href="https://en.wikipedia.org{{dstTitle.0}}">{{dstTitle.1}}</a>. </p>
        </div>

        <div class="Box">
            <div class="searchBox" style="align-self: center">
                {% if isRoute != 0 %}
                The most related route bewteen the source and destination is
                <br>
                <table>
                    {% for d in routeList %}
                        <tr><td>
                                <a href="https://en.wikipedia.org{{d.0}}">{{d.1}}</a>
                        </td></tr>
                    {% endfor %}
                    <tr>
                </table>
                {% else %}
                    <p>No route is found in the dataset...</p>
                {% endif %}
                </ol>
            </div>
            <div style="clear:both;"> </div>
        </div>
        <br>
        <br>
        <h3>Continue exploring WikiNet: </h3>
            
        <div class="Box">
            <div class="searchBox">
                Search here for most related pages. 
                <br>
                <form action=" {% url 'wikiNet:search' %} " method="get">
                <table>
                    <tr>
                        <td><input id="query" type="text" name="query" placeholder="Keywords"></td>
                    </tr>
                    <tr>
                        <td><input type="submit" value="Search for related Pages! "></td>
                    </tr>
                </table>
                </form>
            </div>
            
            <div class="searchBox">
                Search here for the most related path. 
                <br>
                <form action=" {% url 'wikiNet:route' %} " method="get">
                <table>
                    <tr>
                        <td><input id="src" type="text" name="src" placeholder="Source"></td>
                    </tr>
                    <tr>
                        <td><input id="dst" type="text" name="dst" placeholder="Destination"></td> 
                    </tr>
                    <tr>
                        <td><input type="submit" value="Search for most related Path! "></td>
                    </tr>
                </table>
                </form>
            </div>
            <div style="clear:both;"> </div>
        </div>
    </div>

    <br>
    <div style="clear:both;"> </div>
</div>
    <div class="webfooter">
        C. Zhang and G. Yang 
        <br>
        Powered by Django
    </div>
</body>
</html>



<!--<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>wikiNet</title>
    
</head>

<body>

<h3><a href="{% url 'wikiNet:index' %}">Portal</a></h3>

<div class="results">
    <a href="https://en.wikipedia.org{{srcTitle.0}}">{{srcTitle.1}}</a>
    <a href="https://en.wikipedia.org{{dstTitle.0}}">{{dstTitle.1}}</a>
    <br>
    {% if isRoute != 0 %}
    <table>
        {% for d in routeList %}
            <tr><td>
                    <a href="https://en.wikipedia.org{{d.0}}">{{d.1}}</a>
            </td></tr>
        {% endfor %}
        <tr>
    </table>
    {% else %}
        <p>No route is found in the dataset...</p>
    {% endif %}
</div>

<br>
</body>


</html>


-->